pipeline {
    agent {
        kubernetes {
            cloud 'team5-eks'
            yaml """
            apiVersion: v1
            kind: Pod
            spec:
              serviceAccountName: jenkins-admin
            """
        }
    }
    environment {
        APP_NAME = "sparkjava-app"
    }

    stages {
        stage("Checkout from SCM") {
               steps {
                    sh 'pwd'
                    sh 'ls -al'
                    git branch: 'cjh', credentialsId: 'CJH_Github_Credential', url: 'https://github.com/ciscocloud03-team5/gitops-integration'
               }
        }

        // 버전관리
        stage("Update the Deployment Tags") {
            steps {
                script {
                    dir('/home/jenkins/agent/workspace/gitops-sparkjava/sparkjava') {
                        sh """
                        pwd
                        ls -al
                        cat sparkjava_deployment.yaml 
                        sed -i 's/${APP_NAME}.*/${APP_NAME}:${IMAGE_TAG}/g' sparkjava_deployment.yaml
                        cat sparkjava_deployment.yaml
                        """
                    // 배포 yaml 파일명 정확히 작성할 것.
                    }
                }
            }
        }

        stage("Push the changed deployment file to Git") {
            steps {
                script {
                    dir('/home/jenkins/agent/workspace/gitops-sparkjava/sparkjava') {
                        sh """
                            pwd
                            git config --global user.email "cjhcjh0429@gmail.com"
                            git config --global user.name "icebreakerrr"
                            git add sparkjava_deployment.yaml 
                            git commit -m "New Update Of Deployment"
                            """
                        // git add sparkjava_deployment.yaml 
                        // git add ../sparkjava@tmp/                       
                        withCredentials([gitUsernamePassword(credentialsId: 'CJH_Github_Credential', gitToolName: 'Default')]) {
                            sh "git push https://github.com/ciscocloud03-team5/gitops-integration cjh"
                        }
                    }
                }
            }
        }
    }
}