apiVersion: v1
kind: Service
metadata:
  name: pokerogue-service
  namespace: dev
spec:
  selector:
    app: pokerogue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080       
  # following deployment container port 
  # type: ClusterIP