apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: ksi05298/flask-app:1.0.0-61
          resources:
            limits:
              memory: "256Mi"
          ports:
            - containerPort: 5000