apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: dev
  labels:
    app: flask-app 
spec:
  selector:
    app: flask-app
  type: ClusterIP
  ports:
    - name: flask-5000
      port: 5000
      targetPort: 5000