apiVersion: apps/v1
kind: Deployment
metadata:
  name: towergame:1.0.0-8
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: towergame:1.0.0-8
  template:
    metadata:
      labels:
        app: towergame:1.0.0-8
    spec:
      containers:
      - name: towergame:1.0.0-8
        image: spear77/towergame:1.0.0-8
        ports:
        - containerPort: 6027   # EXPOSE PORT와 SYNC
