pipeline {
    agent {
        kubernetes {
            cloud 'team5-eks'
            yaml """
            apiVersion: v1
            kind: Pod
            spec:
              serviceAccountName: jenkins-admin
            """
        }
    }
    environment {
        APP_NAME = "ocr-local"
    }

    stages {
        stage("Checkout from SCM") {
            steps {
                sh 'pwd'
                sh 'ls -al'
                sh 'ls -al soldesk'
                git branch: 'ocr', credentialsId: 'ocr', url: 'https://github.com/ciscocloud03-team5/gitops-integration'
            }
        }

        stage("Update the Deployment Tags") {
            steps {
                script {
                    dir('/home/jenkins/agent/workspace/gitops-ocr/soldesk') {
                        sh """
                        echo "Current directory: $(pwd)"
                        echo "Listing contents:"
                        ls -al
                        echo "Displaying deployment.yaml:"
                        cat deployment.yaml
                        sed -i 's/${APP_NAME}.*/${APP_NAME}:${IMAGE_TAG}/g' deployment.yaml
                        echo "Updated deployment.yaml:"
                        cat deployment.yaml
                        """
                    }
                }
            }
        }

        stage("Push the changed deployment file to Git") {
            steps {
                script {
                    dir('/home/jenkins/agent/workspace/gitops-ocr/soldesk') {
                        sh """
                        echo "Listing contents before git add:"
                        ls -al
                        git config --global user.email "eleys8596@naver.com"
                        git config --global user.name "rootssv"
                        git add deployment.yaml
                        echo "Git status after git add:"
                        git status
                        git commit -m "Updated Deployment Manifest" || echo "No changes to commit"
                        """
                        withCredentials([gitUsernamePassword(credentialsId: 'ocr', gitToolName: 'Default')]) {
                            sh "git push https://github.com/ciscocloud03-team5/gitops-integration ocr"
                        }
                    }
                }
            }
        }
    }
}

