pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Git Config and Commit') {
            steps {
                script {
                    dir('gitops-integration/soldesk') {
                        sh 'git config --global user.email "eleys8596@naver.com"'
                        sh 'git config --global user.name "rootssv"'
                        sh 'git add deployment.yaml'
                        sh '''
                            if git commit -m "Updated Deployment Manifest"; then
                                echo "Commit successful"
                            else
                                echo "Nothing to commit"
                            fi
                        '''
                    }
                }
            }
        }
    }
}
