apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
  namespace: dev
  labels:
    app: flaskapp 
spec:
  selector:
    app: flaskapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
