apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: yunjin6121/flask-local:1.4-33
          resources:
            limits:
              memory: "256Mi"
          ports:
            - containerPort: 8000
