pipeline {
    agent {
        kubernetes {
            cloud 'team5-eks'
            yaml """
            apiVersion: v1
            kind: Pod
            spec:
              serviceAccountName: jenkins-admin
            """
        }
    }
    environment {
        APP_NAME = "flask"
    }

    stages {
        stage("Checkout from SCM") {
               steps {
                        sh 'pwd'
                        sh 'ls -al'
                        sh 'ls -al flask'
                        git credentialsId: 'yunjin6121', // GitHub 자격증명 사용
                          url: 'https://github.com/ciscocloud03-team5/gitops-integration', // GitHub 리포지토리 URL
                          branch: 'yjk' // 브랜치 이름
                    }
             }
        }

        stage("Update the Deployment Tags") {
            steps {
                script {
                    dir('/home/jenkins/agent/workspace/yjk-pipeline/flask') { // 작업 디렉토리 설정
                        sh """
                        pwd
                        ls -al
                        cat deployment.yaml
                        sed -i 's/${APP_NAME}.*/${APP_NAME}:${IMAGE_TAG}/g' deployment.yaml
                        cat deployment.yaml
                        """
                    }
                }
            }
        }

        stage("Push the changed deployment file to Git") {
            steps {
                script {
                    dir('/home/jenkins/agent/workspace/yjk-pipeline/flask') {
                        sh """
                        git config --global user.email "yunjin6121@gmail.com"
                        git config --global user.name "yunjin6121"
                        git add deployment.yaml
                        git commit -m "Updated Deployment Manifest"
                        """
                        withCredentials([gitUsernamePassword(credentialsId: 'yunjin6121', gitToolName: 'Default')]) { // GitHub 자격증명 사용
                            sh "git push https://github.com/ciscocloud03-team5/gitops-integration yjk"
                        }
                    }
                }
            }
        }
    }
}


