pipeline {
    agent {
        kubernetes {
            cloud 'team5-eks'
            yaml """
            apiVersion: v1
            kind: Pod
            spec:
              serviceAccountName: jenkins-admin
            """
        }
    }
    environment {
        APP_NAME = "flask"
    }

    stages {
        stage("Checkout from SCM") {
               steps {
                   git branch: 'yjk', credentialsId: 'yunjin6121', url: 'https://github.com/ciscocloud03-team5/gitops-integration' // github credential
               }
        }

        stage("Update the Deployment Tags") {
            steps {
                script {
                    dir('/home/jenkins/agent/workspace/yjk-pipeline/flask') { // 경로지정
                        sh """
                        cat deployment.yaml
                        sed -i 's/${APP_NAME}.*/${APP_NAME}:${IMAGE_TAG}/g' deployment.yaml
                        cat deployment.yaml
                        """
                    }
                }
            }
        }

        stage("Push the changed deployment file to Git") {
            steps {
                script {
                    dir('/home/jenkins/agent/workspace/yjk-pipeline/flask'') {
                        sh """
                        git add deployment.yaml
                        git commit -m "Updated Deployment Manifest"
                        """
                        withCredentials([gitUsernamePassword(credentialsId: 'yunjin6121', gitToolName: 'Default')]) { // github credential 
                            sh "git push https://github.com/ciscocloud03-team5/gitops-integration yjk"
                        }
                    }
                }
            }
        }
    }
}


